# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fda2a16ad945be74d62e1e90119a7201a0f8b0012c1ad0a1a54822f22787a5183c721f838cfb60bafd76ce93036f040634cc42318bf164507d64b560cec3d40c

test:
  secret_key_base: f2772c247da7e55ef3803fa602c07947504eacb5ba7cca0c5b9b8539a5e73f49f8b8a901402aa235169552e11084dd1b6af54c8b1533a5bc5901c828f0b98dd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
